
GET http://localhost:3333/api/posts?skip=4&limit=9

###

GET http://localhost:3333/api/posts/11

###

GET http://localhost:3333/api/posts


###

Post http://localhost:3333/api/posts
Content-Type: application/json

{
    "title": "Post api 1234",
    "text": "Some text param FROM api1234", 
}

###

PATCH  http://localhost:3333/api/posts/15
Content-Type: application/json

{
    "title": "Post API Deleted",
    "text": "Some text param FROM api13456" 
}

###

DELETE   http://localhost:3333/api/posts/39

###Users

GET http://localhost:3333/api/users?skip=0&limit=2

###

GET http://localhost:3333/api/users

###

GET http://localhost:3333/api/users/2

###

Post http://localhost:3333/api/users
Content-Type: application/json

{
    "email": "MAD13145@mail.ru",
    "name": "MADANDD",
    "password": "12134"
}

###

PATCH  http://localhost:3333/api/users/30
Content-Type: application/json

{
    "email": "MAD13456@mail.ru",
    "name": "MAD",
    "password": "1213"
}

###

DELETE   http://localhost:3333/api/users/29

###

POST http://localhost:3333/api/login
Content-Type: application/json

{
    "email": "test1@mail.ru",
    "password": "test123"
}

###

POST http://localhost:3333/api/signup
Content-Type: application/json

{
    "email": "Andriy@ukr.ua",
    "name": "Andriy",
    "password": "12345"
}

###

GET http://localhost:3333/api/users/14
